FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

ARG APP_VERSION=unknown
ENV APP_VERSION=$APP_VERSION

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "scanner.py"]
