version: '3'

tasks:
  up:
    desc: Rebuild and run the project locally
    vars:
      GIT_VERSION:
        sh: git describe --tags --always --dirty || echo "unknown"
    cmds:
      - APP_VERSION={{.GIT_VERSION}} docker compose up --build -d
      - echo "App ({{.GIT_VERSION}}) is running at http://localhost:7880"

  down:
    desc: Stop the local project
    cmds:
      - docker compose down

  clean:
    desc: Remove all containers, volumes (including Redis data), and local images
    cmds:
      - docker compose down -v --rmi local

  flush:
    desc: Flush only the Redis database (deletes all cached photo metadata)
    cmds:
      - docker exec -it $(docker ps -q -f name=redis) redis-cli FLUSHALL
      - echo "Redis database flushed."

  release:
    desc: "Create a new release tag and push it (usage: task release -- v1.0.0)"
    vars:
      TAG: '{{.VERSION | default .CLI_ARGS}}'
    cmds:
      - 'test -n "{{.TAG}}" || (echo "Error: Version argument required (e.g. task release v1.0.0)" && exit 1)'
      - 'git tag -a {{.TAG}} -m "Release {{.TAG}}"'
      - 'git push origin {{.TAG}}'
    silent: true
