version: '3'

tasks:
  release:
    desc: "Create a new release tag and push it (usage: task release -- v1.0.0)"
    vars:
      TAG: '{{.VERSION | default .CLI_ARGS}}'
    cmds:
      - 'test -n "{{.TAG}}" || (echo "Error: Version argument required (e.g. task release v1.0.0)" && exit 1)'
      - 'git tag -a {{.TAG}} -m "Release {{.TAG}}"'
      - 'git push origin {{.TAG}}'
    silent: true
